// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  firebase: {
    apiKey: "AIzaSyDB7ky02zQGeLWRI43zJkTg3NETmbLzYhI",
    authDomain: "aid4kids-3342e.firebaseapp.com",
    databaseURL: "https://aid4kids-3342e.firebaseio.com",
    projectId: "aid4kids-3342e",
    storageBucket: "aid4kids-3342e.appspot.com",
    messagingSenderId: "152281807638"
  },
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
