// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  firebase: {
    apiKey: "AIzaSyC1lhQgXW-08ttzTrSktVvNTFCA1HVLpw4",
    authDomain: "aid4kids-ed95a.firebaseapp.com",
    databaseURL: "https://aid4kids-ed95a.firebaseio.com",
    projectId: "aid4kids-ed95a",
    storageBucket: "aid4kids-ed95a.appspot.com",
    messagingSenderId: "776583101410"
  },
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
