// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  firebase: {
    apiKey: "AIzaSyC1lhQgXW-08ttzTrSktVvNTFCA1HVLpw4",
    authDomain: "aid4kids-ed95a.firebaseapp.com",
    databaseURL: "https://aid4kids-ed95a.firebaseio.com",
    projectId: "aid4kids-ed95a",
    storageBucket: "aid4kids-ed95a.appspot.com",
    messagingSenderId: "776583101410"
  },
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};




export const envtest = {
  production: false,
  version: env.npm_package_version + '-dev',
  firebase: {
    apiKey: "AIzaSyC1lhQgXW-08ttzTrSktVvNTFCA1HVLpw4",
    authDomain: "aid4kids-ed95a.firebaseapp.com",
    databaseURL: "https://aid4kids-ed95a.firebaseio.com",
    projectId: "aid4kids-ed95a",
    storageBucket: "aid4kids-ed95a.appspot.com",
    messagingSenderId: "776583101410"
  },
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};